// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/portfolio.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requête pour obtenir la valeur du portefeuille
type GetPortfolioValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioValueRequest) Reset() {
	*x = GetPortfolioValueRequest{}
	mi := &file_api_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioValueRequest) ProtoMessage() {}

func (x *GetPortfolioValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioValueRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioValueRequest) Descriptor() ([]byte, []int) {
	return file_api_portfolio_proto_rawDescGZIP(), []int{0}
}

// Réponse contenant la valeur du portefeuille
type GetPortfolioValueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Valeur totale du portefeuille en EUR
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Devise de la valeur (toujours EUR pour cet exercice)
	Currency string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	// Timestamp de la dernière mise à jour des prix
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioValueResponse) Reset() {
	*x = GetPortfolioValueResponse{}
	mi := &file_api_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioValueResponse) ProtoMessage() {}

func (x *GetPortfolioValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioValueResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioValueResponse) Descriptor() ([]byte, []int) {
	return file_api_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *GetPortfolioValueResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetPortfolioValueResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPortfolioValueResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_portfolio_proto protoreflect.FileDescriptor

const file_api_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x13api/portfolio.proto\x12\tportfolio\"\x1a\n" +
	"\x18GetPortfolioValueRequest\"k\n" +
	"\x19GetPortfolioValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2r\n" +
	"\x10PortfolioService\x12^\n" +
	"\x11GetPortfolioValue\x12#.portfolio.GetPortfolioValueRequest\x1a$.portfolio.GetPortfolioValueResponseB'Z%github.com/xAPT42/dual-api-crypto/apib\x06proto3"

var (
	file_api_portfolio_proto_rawDescOnce sync.Once
	file_api_portfolio_proto_rawDescData []byte
)

func file_api_portfolio_proto_rawDescGZIP() []byte {
	file_api_portfolio_proto_rawDescOnce.Do(func() {
		file_api_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_portfolio_proto_rawDesc), len(file_api_portfolio_proto_rawDesc)))
	})
	return file_api_portfolio_proto_rawDescData
}

var file_api_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_portfolio_proto_goTypes = []any{
	(*GetPortfolioValueRequest)(nil),  // 0: portfolio.GetPortfolioValueRequest
	(*GetPortfolioValueResponse)(nil), // 1: portfolio.GetPortfolioValueResponse
}
var file_api_portfolio_proto_depIdxs = []int32{
	0, // 0: portfolio.PortfolioService.GetPortfolioValue:input_type -> portfolio.GetPortfolioValueRequest
	1, // 1: portfolio.PortfolioService.GetPortfolioValue:output_type -> portfolio.GetPortfolioValueResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_portfolio_proto_init() }
func file_api_portfolio_proto_init() {
	if File_api_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_portfolio_proto_rawDesc), len(file_api_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_portfolio_proto_goTypes,
		DependencyIndexes: file_api_portfolio_proto_depIdxs,
		MessageInfos:      file_api_portfolio_proto_msgTypes,
	}.Build()
	File_api_portfolio_proto = out.File
	file_api_portfolio_proto_goTypes = nil
	file_api_portfolio_proto_depIdxs = nil
}
